config/routes.rb
Lsssp::Application.routes.draw do

  resources :payments

  resources :examinations

#  resources :questionbanks

  resources :subjects

  resources :users do
     get 'upload', :on=>:collection
     get 'export', :on=>:collection
     get 'search', :on=>:collection
#     get 'update_password',:on=>:collection
#     get 'resetpassword', :on=>:member
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  resources :registrations
 
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
#  get "subjects/index"
#  get "subjects/new"
#  match "admin/subjects" => "subjects#index", :as => :subject
#  match "admin/subjects/new" =>"subjects#new", :as => :new_subject

  
  root :to => "user_sessions#new"
    
  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :assignments
  has_many :roles, :through => :assignments
  
  validates_presence_of :mobile_number, :message=>"Primary Contact Number"
  #validates :phone_number, :presence => true

  validates :first_name, :presence => true
  validates :last_name, :presence =>true
  validates_presence_of :password, :password_confirmation
  validates_confirmation_of :password
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def self.search(search)
    if search
      where({:email.matches => "%#{search}%"} | {:first_name.matches => "%#{search}%"} |
     {:last_name.matches => "%#{search}%"} | {:enrollment_number.matches => "%#{search}%"} )
    else
      scoped
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.deliver_password_reset_instructions(self)
  end

end

app/controllers/users_controller.rb
require 'csv'

class UsersController < ApplicationController
  layout 'admin'

  #before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:index,:show, :edit, :update]
  def index
    @users = User.search(params[:search]).order('created_at DESC').paginate(:page=>params[:page],:per_page=>20 )
  #   @users, @paginator = User.alpha_scope :email, params[:ltr]
  end

  def new
    @user = User.new
    @enrollment_number  = rand(1000000000-9999999999)

  end

  def create
    @user = User.new(params[:user])

#    @user.password = @user.password_confirmation = params[:user][:email]
    @user.created_by = @created_by
    @user.status = "Not Approved"

#    enrollment_number  = rand(1000000000-9999999999)
#    @user.enrollment_number = enrollment_number
    respond_to do |format|
      if @user.save
        #send mail
        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to(users_path, :notice => 'User was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    #    params[:user][:role_ids] ||= []

    @user.updated_by = @updated_by
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def csv_import
    csv_file = params[:upload][:file]
    n=0
    CSV.new(csv_file.tempfile,:col_sep => ",").each do |row|
      @user = User.create do |u|
        u.first_name  =row[0]
        u.last_name = row[1]
        u.email = row[2]
        u.password = u.password_confirmation = row[2]
        u.phone_number = row[4]
        u.mobile_number = row[3]
        u.status = 'Not Approved'
        u.created_by = 2
        u.updated_by=2
        u.enrollment_number = rand(1000000000-9999999999)
      end
      UserMailer.welcome_email(@user).deliver
      @user.save
      n=n+1
    end
    flash[:notice]= "#{n} Users are imported sucessfully"
    respond_to do |format|
      format.html { redirect_to(users_path) }
      format.xml  { head :ok }
    end
  end

  def upload
  end

  def export
    @users = User.all
    outfile = "LSSP Users" + Time.now.strftime("%d-%m-%Y") + ".csv"
    csv_data = CSV.generate do |csv|
      csv << ["Enrollment Number","First Name","Last Name","Email","Mobile Number","Phone Number"]
      @users.each do |user|
        csv << [user.enrollment_number,user.first_name,user.last_name,user.email,user.mobile_number,user.phone_number]
      end
    end
    send_data csv_data,
    :type => 'text/csv; charset=iso-8859-1; header=present',
    :disposition => "attachment; filename=#{outfile}"
  end
  
  def resetpassword
    @user = User.find(params[:id])
    @user.password= @user.password_confirmation=@user.enrollment_number
    @user.status = "Not Approved"
   respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(users_path, :notice => 'User Password is  successfully Reset.') }
        format.xml  { head :ok }
        UserMailer.resetpassword_email(@user).deliver
      else
      end
  end
  end
end

app/views/users/_form.erb
       <%= form_for @user, :url =>{:action => "create"} do |f| %>
        <div class="tabless">
            <div style="position: relative; left: 0px; top: 0px;" class="standalone" id="standalone">
                <div class="title">
                    Enter Details for Registration<br>
					   </div>
				<p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
                <div class="section">
                    <div class="label">
                        First Name:<em><font color="red">*</font></em>
                    </div>
                    <%= f.text_field :first_name,:size=>30 %>
                    <div class="label">
                        Last Name:<em><font color="red">*</font></em>
                    </div>
                    <%= f.text_field :last_name,:size=>30 %>
                    <div class="label">
                        Email:<em><font color="red">*</font></em>
                    </div>
                    <%= f.text_field :email,:size=>30 %>
                    <%= f.hidden_field :password, :value=>@enrollment_number%>
                    <%= f.hidden_field :password_confirmation, :value=>@enrollment_number %>
					<%= f.hidden_field :enrollment_number, :value=>@enrollment_number %>
                    <div class="label">
                        Primary Contact Number:<em><font color="red">*</font></em> (Mobile/Telephone. Ex:+04412345678)
                    </div>
                    <%= f.text_field :mobile_number, :size=>30 %>
					 <div class="label">
                        Secondary Contact Number: (Mobile/Telephone. Ex:+04412345678)
                    </div>
                    <%= f.text_field :phone_number, :size=>30 %>
                </div>
				
                <div class="buttonbar">
                    <%= f.submit "Save" %>
                </div>
                <% end %>
            </div>
        </div>

app/views/users/edit.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Update',:heading=>'Edit user'} %>
<div class="bottom_links">
    <a href="/users" class="more">All users</a>
    <%= link_to [@user],:class=>'more' do %>
    Show <% end %>
</div>

app/views/users/index.html.erb
<h1>List of  Users</h1>
<div>
<table>
<tr>
<td><%=link_to new_user_path,:class=>'more' do %>Create New User<% end %></td>
<td><%= link_to 'Import Users',{:action=>'upload'},:class=>'more' %></td>
<td><%= link_to 'Export Users',{:action=>'export'},:class=>'more' %></td>
<td width="550" align=right>
	<%= form_tag(controller_name, :method => 'get') do %>
	<%= text_field_tag :search, params[:search], :maxlength => 25, :class => "searchfield" %>
	<%= submit_tag "Search"%>
	<% end %>
</td>
</tr>
</table>
</div>
<table id="box-table-a">
	<tr>
		<th scope="col"> SNo</th>
		<th scope="col"> Enrollment #</th>
		<th scope="col"> First Name</th>
		<th scope="col"> Last Name</th>
		<th scope="col"> Email</th>
		<th scope="col"> Created On</th>
		<th scope='col'> Status</th>
		<th scope="col"> Actions</th>
	</tr>
	<% i = 1%>
	<% @users.each do |user| %>
	<tr>
		<td><%= i%></td>
		<td> <%= user.enrollment_number%></td>
		<td> <%= highlight(user.first_name,params[:search]) %></td>
		<td> <%= highlight(user.last_name,params[:search]) %></td>
		<td> <%= highlight(user.email,params[:search]) %></td>
		<td> <%= user.created_at.strftime('%d-%b-%Y')%></td>
		<td> <%if user.status == "Not Approved" %>
				Pending
			 <%else%>
					<%if user.verified_date?%>
					<%= user.verified_date.strftime('%d-%b-%Y')%>
					<%else%>
					<%end%>
			 <%end%>
		</td>
		<td> <%= link_to 'View', user %> | <%= link_to 'Edit', edit_user_path(user) %>
		<% unless (user.id == 1 || user.id == 2) %> |
		<%= link_to('Delete', user, :confirm => 'Are you sure?', :method => :delete)  %> | 
		<%= link_to 'Reset Password',:action=>'resetpassword',:id=>user.id%> | 
		<%= link_to 'Assign Exam', :controller => "userexaminations", :action=>"new", :user_id=> user.id %> | 
		<%= link_to 'Exam Status', :controller => "userexaminations", :action=>"exam_status", :user_id=> user.id %></td>
		<% end %>
		</td>
	</tr>
	<% i = i + 1%>
	<% end %>
</table>
<div class="flickr_pagination">
	<%= will_paginate @users, :container => false %>
	<div class='page_info'>
		<%= page_entries_info @users, :entry_name => 'Users' %>
	</div>
</div>

app/views/users/new.html.erb
<%=render :partial=>'form',:locals=>{:button_name=>'Create',:heading=>'Create user'} %>
<br>
<div class="bottom_links">
    <a href="/users" class="more">List All users</a>
</div>

app/views/users/reset.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
        <title>LSSSP</title>
        <%= javascript_include_tag 'rails','application' %>
        <%= stylesheet_link_tag 'admin_screen' %>
        <%= csrf_meta_tag %>
    </head>
    <body>
        <div id="header">
            <%=link_to image_tag("adminlogo.png"),root_url %>
        </div>
        <div class="tabless">
        <div style="position: relative; left: 0px; top: 0px;" class="standalone" id="standalone">
            <%=render :partial=>'/import_flash' %>
        </div>
        <center>
            <div id="footer">
                © 2011
            </div>
        </center>
    </body>
</html>

app/views/users/show.html.erb
<div class="form-container">
    <fieldset>

        <div>
            <label>
                <b>First Name:</b>
            </label>
            <%=h @user.first_name %>
        </div>
        <hr/>
		        <div>
            <label>
                <b>Last Name:</b>
            </label>
            <%=h @user.last_name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Email:</b>
            </label>
            <%=h @user.email %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Mobile:</b>
            </label>
            <%=h @user.mobile_number %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Enrollment Number:</b>
            </label>
            <%=h @user.enrollment_number %>
        </div>
        <hr/>
 
        <div>
            <label>
                <b>Phone:</b>
            </label>
            <%=h @user.phone_number %>
        </div>
        <hr/>
    </fieldset>
</div>
<div class="bottom_links">
    <%= link_to edit_user_path(@user),:class=>'more' do %>
    Edit<% end %>
    &nbsp;&nbsp;<a href="/users" class="more">All Users</a>
    &nbsp;&nbsp;
</div>

app/views/users/upload.html.erb
<% form_for :upload, :url=>{:controller=>"users",:action=>"csv_import"},:html => { :multipart => true } do |f| -%>
<table>
<tr>
    <td>
        <label for="vle_user">
            Select a CSV File :
        </label>
    </td>
    <td>
        <%= f.file_field :file -%>
    </td>
</tr>
<tr>
    <td colspan='2'>
        <%= submit_tag 'Submit' -%>
    </td>
</tr>
</table>
<% end -%>