config/routes.rb
Lsssp::Application.routes.draw do

  resources :payments

  resources :examinations

#  resources :questionbanks

  resources :subjects

  resources :users do
     get 'upload', :on=>:collection
     get 'export', :on=>:collection
     get 'search', :on=>:collection
#     get 'update_password',:on=>:collection
#     get 'resetpassword', :on=>:member
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  resources :registrations
 
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
#  get "subjects/index"
#  get "subjects/new"
#  match "admin/subjects" => "subjects#index", :as => :subject
#  match "admin/subjects/new" =>"subjects#new", :as => :new_subject

  
  root :to => "user_sessions#new"
    
  match ':controller(/:action(/:id(.:format)))'
end

app/models/activetest.rb
class Activetest < ActiveRecord::Base

end

app/models/activexam.rb
class Activexam < ActiveRecord::Base
#	has_many :questionbanks
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/examination.rb
class Examination < ActiveRecord::Base
  #  has_and_belongs_to_many :userexaminations
  validates :examname,:duration,:passmarks,:positivemarks, :presence => true
  validates_numericality_of :passmarks,:positivemarks,:duration,:greater_than_or_equal_to=>1
  
  validates_numericality_of :negativemarks,:notattemptmarks,:greater_than_or_equal_to=>0
  
 
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/questionbank.rb
class Questionbank < ActiveRecord::Base
  belongs_to :subject
  belongs_to :activexam
  validates_attachment_presence :question, :if => "question_text.blank?"
  validates_attachment_presence :option1, :if => "option1_text.blank?"
  validates_attachment_presence :option2, :if => "option2_text.blank?"
  
  validates :correct_answer ,:presence=>true
=begin  
  def validate
    unless option1_text_check || option2_text_check || option3_text_check || option4_text_check || option5_text_check
      errors.add_to_base "at least one checkbox from answer1,  or answer2 or answer3 or answer4 or answer5 must be checked"
    end
  end
=end  
  
  has_attached_file :question, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option1, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option2, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option3, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option4, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option5, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :questionbanks,:dependent=>:destroy
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :assignments
  has_many :roles, :through => :assignments
  
  validates_presence_of :mobile_number, :message=>"Primary Contact Number"
  #validates :phone_number, :presence => true

  validates :first_name, :presence => true
  validates :last_name, :presence =>true
  validates_presence_of :password, :password_confirmation
  validates_confirmation_of :password
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def self.search(search)
    if search
      where({:email.matches => "%#{search}%"} | {:first_name.matches => "%#{search}%"} |
     {:last_name.matches => "%#{search}%"} | {:enrollment_number.matches => "%#{search}%"} )
    else
      scoped
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.deliver_password_reset_instructions(self)
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

app/models/userexamination.rb
class Userexamination < ActiveRecord::Base
	belongs_to :examination
  belongs_to :user
  validates_uniqueness_of :examination_id, :scope => :user_id
#    has_and_belongs_to_many :examinations
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout "admin"
  before_filter :require_user, :only => [:index,:show, :edit, :update]
  
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subjects }
    end
  end

  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subject }
    end
  end

  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subject }
    end
  end


  def edit
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(params[:subject])
    

    respond_to do |format|
      if @subject.save
        format.html { redirect_to(@subject, :notice => 'Module was successfully created.') }
        format.xml  { render :xml => @subject, :status => :created, :location => @subject }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to(@subject, :notice => 'Module was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subject.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to(subjects_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/activetests_helper.rb
module ActivetestsHelper
end

app/helpers/activexam_helper.rb
module ActivexamHelper
end

app/helpers/adminindex_helper.rb
module AdminindexHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def admin_tabs
    html = ''
    super_admin = Role.find_by_name('super_admin')
    admin = Role.find_by_name('admin')
    if current_user.roles.include?(super_admin) 
      
      html << "<li>"
      html << link_to('Users',{:controller=>'user',:action=>'index'},:class=>(current_page?(:controller=>'user',:action=>'index') ? "users selected" : ""))
      html << "</li>"


            
    elsif current_user.roles.include?(admin) 
      
      html <<  '<li>'
      html << link_to('Module',{:controller=>'subjects',:action=>'index'},:class=>(current_page?(:controller=>'subjects',:action=>'index') ? "subjects selected" : ""))
      html << '</li>'
     
      html <<  '<li>'
      html << link_to('Examination',{:controller=>'examinations',:action=>'index'},:class=>(current_page?(:controller=>'examinations',:action=>'index') ? "examinations selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Payment',{:controller=>'payments',:action=>'index'},:class=>(current_page?(:controller=>'payments',:action=>'index') ? "payments selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Users',{:controller=>'users',:action=>'index'},:class=>(current_page?(:controller=>'users',:action=>'index') ? "users selected" : ""))
      html << '</li>'

     end 
    html.html_safe
  end

  def student_tabs
    html = ''
      html << "<li>"
      html << link_to('Examination',{:controller=>'activetests',:action=>'index'},:class=>(controller_name.eql?('activetests') ? "activetests" : "")) 
      html << "</li>"

     html << "<li>"
      html << link_to('Services',{:controller=>'services',:action=>'index'},:class=>(controller_name.eql?('services') ? "active" : "")) 
      html << "</li>"
      
      
    html.html_safe
  end   
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/helpers/firstlogins_helper.rb
module FirstloginsHelper
end

app/helpers/forgotpass_helper.rb
module ForgotpassHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<div class="form-container">
    <%= form_for(@subject) do |f| %>
    <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
    </p>
	<fieldset>
    <%=f.error_messages %>
    <div>
        <label for="name">
            Name <em>*</em>
        </label>
        <%= f.text_field :name %>
    </div>
    <div>
        <label for="description ">
            Description
        </label>
        <%= f.text_area :description ,:cols=>28,:rows=>5 %>
    </div>
    <div class="buttonrow">
        <%= f.submit "Create" %>
    </div>
	</fieldset>
    <% end %>
</div>

app/views/subjects/edit.html.erb
<h1>Edit Module</h1>
<%= render 'form' %>
<div class="bottom_links">
    <%= link_to 'All Modules', subjects_path ,:class=>'more' %>
    <%= link_to 'View', @subject ,:class=>'more' %>
</div>

app/views/subjects/index.html.erb
<h1>List Modules</h1>
<%if @subjects.blank? %>
<b>There are No Examinations yet..!</b>
<%else %>
<table id="box-table-a" > 
    <tr>
        <th scope="col">
            SNo
        </th>
        <th scope="col">
            Module
        </th>
        <th scope="col">
            Actions
        </th>
    </tr>
    <% i = 1 %>
    <% @subjects.each do |subject| %>
    <tr>
        <td>
            <%= i %>
        </td>
        <td>
            <%= subject.name %>
        </td>
        <td>
            <%= link_to 'View', subject %>| <%= link_to 'Edit', edit_subject_path(subject) %> | <%= link_to 'Delete', subject, :confirm => 'Are you sure?', :method => :delete %> | <%= link_to 'Create Question Bank', :controller => "questionbanks", :action=>"new", :module_id=>subject.id %>
        </td>
    </tr>
    <% i = i + 1 %>
    <% end %>
</table>
<% end %>
<br/>
<%= link_to 'New Module', new_subject_path,:class=>'more' %>

app/views/subjects/new.html.erb
<h1>New Module</h1>
<%= render 'form' %>

app/views/subjects/show.html.erb
<div class="form-container">
    <fieldset>
        <div>
            <label>
                <b>Name:</b>
            </label>
            <%=h @subject.name %>
        </div>
        <hr/>
        <div>
            <label>
                <b>Description:</b>
            </label>
            <%=h @subject.description %>
        </div>
        <hr/>
    </fieldset>
</div>
<div class="bottom_links">
    <a href="/subjects" class="more">All Modules</a>
    &nbsp;&nbsp;<%= link_to edit_subject_path(@subject),:class=>'more' do %>
    Edit <% end %>
    &nbsp;&nbsp;<%=link_to new_subject_path,:class=>'more' do %>
    Create New Module <% end %>
</div>