config/routes.rb
Lsssp::Application.routes.draw do

  resources :payments

  resources :examinations

#  resources :questionbanks

  resources :subjects

  resources :users do
     get 'upload', :on=>:collection
     get 'export', :on=>:collection
     get 'search', :on=>:collection
#     get 'update_password',:on=>:collection
#     get 'resetpassword', :on=>:member
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  
  resources :registrations
 
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
#  get "subjects/index"
#  get "subjects/new"
#  match "admin/subjects" => "subjects#index", :as => :subject
#  match "admin/subjects/new" =>"subjects#new", :as => :new_subject

  
  root :to => "user_sessions#new"
    
  match ':controller(/:action(/:id(.:format)))'
end

app/models/activetest.rb
class Activetest < ActiveRecord::Base

end

app/models/activexam.rb
class Activexam < ActiveRecord::Base
#	has_many :questionbanks
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/examination.rb
class Examination < ActiveRecord::Base
  #  has_and_belongs_to_many :userexaminations
  validates :examname,:duration,:passmarks,:positivemarks, :presence => true
  validates_numericality_of :passmarks,:positivemarks,:duration,:greater_than_or_equal_to=>1
  
  validates_numericality_of :negativemarks,:notattemptmarks,:greater_than_or_equal_to=>0
  
 
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/questionbank.rb
class Questionbank < ActiveRecord::Base
  belongs_to :subject
  belongs_to :activexam
  validates_attachment_presence :question, :if => "question_text.blank?"
  validates_attachment_presence :option1, :if => "option1_text.blank?"
  validates_attachment_presence :option2, :if => "option2_text.blank?"
  
  validates :correct_answer ,:presence=>true
=begin  
  def validate
    unless option1_text_check || option2_text_check || option3_text_check || option4_text_check || option5_text_check
      errors.add_to_base "at least one checkbox from answer1,  or answer2 or answer3 or answer4 or answer5 must be checked"
    end
  end
=end  
  
  has_attached_file :question, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option1, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option2, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option3, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option4, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :option5, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :questionbanks,:dependent=>:destroy
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :assignments
  has_many :roles, :through => :assignments
  
  validates_presence_of :mobile_number, :message=>"Primary Contact Number"
  #validates :phone_number, :presence => true

  validates :first_name, :presence => true
  validates :last_name, :presence =>true
  validates_presence_of :password, :password_confirmation
  validates_confirmation_of :password
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def self.search(search)
    if search
      where({:email.matches => "%#{search}%"} | {:first_name.matches => "%#{search}%"} |
     {:last_name.matches => "%#{search}%"} | {:enrollment_number.matches => "%#{search}%"} )
    else
      scoped
    end
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.deliver_password_reset_instructions(self)
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

app/models/userexamination.rb
class Userexamination < ActiveRecord::Base
	belongs_to :examination
  belongs_to :user
  validates_uniqueness_of :examination_id, :scope => :user_id
#    has_and_belongs_to_many :examinations
end

app/helpers/activetests_helper.rb
module ActivetestsHelper
end

app/helpers/activexam_helper.rb
module ActivexamHelper
end

app/helpers/adminindex_helper.rb
module AdminindexHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def admin_tabs
    html = ''
    super_admin = Role.find_by_name('super_admin')
    admin = Role.find_by_name('admin')
    if current_user.roles.include?(super_admin) 
      
      html << "<li>"
      html << link_to('Users',{:controller=>'user',:action=>'index'},:class=>(current_page?(:controller=>'user',:action=>'index') ? "users selected" : ""))
      html << "</li>"


            
    elsif current_user.roles.include?(admin) 
      
      html <<  '<li>'
      html << link_to('Module',{:controller=>'subjects',:action=>'index'},:class=>(current_page?(:controller=>'subjects',:action=>'index') ? "subjects selected" : ""))
      html << '</li>'
     
      html <<  '<li>'
      html << link_to('Examination',{:controller=>'examinations',:action=>'index'},:class=>(current_page?(:controller=>'examinations',:action=>'index') ? "examinations selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Payment',{:controller=>'payments',:action=>'index'},:class=>(current_page?(:controller=>'payments',:action=>'index') ? "payments selected" : ""))
      html << '</li>'
      
      html <<  '<li>'
      html << link_to('Users',{:controller=>'users',:action=>'index'},:class=>(current_page?(:controller=>'users',:action=>'index') ? "users selected" : ""))
      html << '</li>'

     end 
    html.html_safe
  end

  def student_tabs
    html = ''
      html << "<li>"
      html << link_to('Examination',{:controller=>'activetests',:action=>'index'},:class=>(controller_name.eql?('activetests') ? "activetests" : "")) 
      html << "</li>"

     html << "<li>"
      html << link_to('Services',{:controller=>'services',:action=>'index'},:class=>(controller_name.eql?('services') ? "active" : "")) 
      html << "</li>"
      
      
    html.html_safe
  end   
end

app/helpers/forgotpass_helper.rb
module ForgotpassHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/common/_footer.html.erb
<center>
<div id="footer">
   © 2011. This site is compatible with Google Chorme and Mozilla 3 and above.
</div>
</center>
</body>
</html>

app/views/common/_header.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title>LSSSP</title>
		<%= javascript_include_tag 'application','jquery-1.5.2.min','rails','jquery.simplemodal','facebox','jquery-ui-1.8.13.custom.min' %>
		<%= stylesheet_link_tag 'admin_screen','confirm' ,'facebox' %>
		<%= csrf_meta_tag %>
		<script type="text/javascript">
				jQuery(document).ready( function($) {
				$('a[rel*=facebox]').facebox()
			})</script>
		<script language="javascript">
				$(document).bind('reveal.facebox', function() {
				$('#facebox').draggable();
			})</script>
	</head>
	<body id="store">
		<div id="header">
			<div id="welcome">
				Welcome,
				<span id="welcome_username"><%= current_user.first_name %></span>
				<span>!&nbsp;&nbsp;</span>
				|<%= link_to 'Profile',:controller=>'/student',:action=>'show',:id=>current_user.id %>
				| <%= link_to 'Logout',logout_path %>
			</div>
			<%= link_to image_tag("adminlogo.png",:border => 0),root_url%>
		</div>
		<div id="tabs">
			<ul>
				<%= student_tabs %>
			</ul>
		</div>

app/views/common/_import_flash.html.erb
<div id="flash_messages">
    <%- flash.each do |name, msg| -%>
    <%= content_tag :div, msg, :id => "flash_#{name}",:class =>"flash_#{name}" %>
    <%end%>
</div>

app/views/notifier/password_reset_instructions.html.erb
<h1>Password Reset Instructions</h1>

<p>
  A request to reset your password has been made. Please follow the link below.
</p>

<%= link_to "Reset Password!", @edit_password_reset_url %>

app/views/score_card/score_card.html.erb
        <% total_correct_answers = 0 %>
		<% total_notattemted_questions = 0 %>
        <% for active_exam in @active_exams %>
        <% total_correct_answers += 1 if Questionbank.find(active_exam.question_id).correct_answer == active_exam.answer %>
        <% total_notattemted_questions +=1 if active_exam.answer.nil? %>
        <% end %>
        <% total_answered = @total_questions - total_notattemted_questions %>
        <% total_wrong_answers = total_answered - total_correct_answers %>
        <br/>
        <% total_marks = (@examination.positivemarks * total_correct_answers)-(total_wrong_answers * @examination.negativemarks)-(total_notattemted_questions * @examination.notattemptmarks) %>
        <% total_exam_marks = @total_questions * @examination.positivemarks%>
		<% total_percentage = ((total_marks.to_f / (@total_questions * @examination.positivemarks)) * 100.0).to_i %>
        <h3>Hi, <%=@user.first_name %></h3>
        <p>
            Your details as per our record:
            <br>
            Enrolment number:<%=@user.enrollment_number%>
            <br/>
            First name: <%=@user.first_name %>
            <br/>
            Last name: <%=@user.last_name %>
            <br/>
            Email: <%=@user.email %>
            <br/>
            Mobile number: <%=@user.mobile_number %>
            <br/>
            Phone number: <%=@user.phone_number %>
            <br/>
        </p>
        <br/>
        <p>
            Your recent Exam completed as per our record:
            <br/>
            Exam name: <%=@examination.examname %>
            <br/>
			<%if @exam_active.result_status == true%>
            Exam status: <font color="green">PASSED </font>
			<%else%>
			           Exam status: <font color="red">FAIL </font>
					  <%end%>
            <br/>
            Exam duration: <%=@examination.duration %>
            <br/>
            Total Exam questions: <%= @total_questions %>
            <br/>
            Total correct answers:<%= total_correct_answers%>
            <br/>
            You got <%= total_percentage%>% while the minimum passing is <%= @examination.passmarks%>% 
        </p>

app/views/score_card/score_card_admin.html.erb
        <% total_correct_answers = 0 %>
        <% total_notattemted_questions = 0 %>
        <% for active_exam in @active_exams %>
        <% total_correct_answers += 1 if Questionbank.find(active_exam.question_id).correct_answer == active_exam.answer %>
        <% total_notattemted_questions +=1 if active_exam.answer.nil? %>
        <% end %>
        <% total_answered = @total_questions - total_notattemted_questions %>
        <% total_wrong_answers = total_answered - total_correct_answers %>
        <br/>
        <% total_marks = (@examination.positivemarks * total_correct_answers)-(total_wrong_answers * @examination.negativemarks)-(total_notattemted_questions * @examination.notattemptmarks) %>
        <% total_exam_marks = @total_questions * @examination.positivemarks %>
        <% total_percentage = ((total_marks.to_f / (@total_questions * @examination.positivemarks)) * 100.0).to_i %>
        <h3>Hi, <%=@user.first_name %></h3>
        <p>
            Your details as per our record:
            <br>
            Enrolment number:<%=@user.enrollment_number%>
            <br/>
            First name: <%=@user.first_name %>
            <br/>
            Last name: <%=@user.last_name %>
            <br/>
            Email: <%=@user.email %>
            <br/>
            Mobile number: <%=@user.mobile_number %>
            <br/>
            Phone number: <%=@user.phone_number %>
            <br/>
        </p>
        <br/>
        <p>
            Your recent Exam completed as per our record:
            <br/>
            Exam name: <%=@examination.examname %>
            <br/>
            <%if @exam_active.result_status == true %>
            Exam status: 
            <font color="green">
                PASSED 
            </font>
            <%else %>
            Exam status: 
            <font color="red">
                FAIL 
            </font>
            <%end %>
            <br/>
            Exam duration: <%=@examination.duration %>
            <br/>
            Total Exam questions: <%= @total_questions %>
            <br/>
            Total correct answers:<%= total_correct_answers %>
            <br/>
            You got <%= total_percentage %>% while the minimum passing is <%= @examination.passmarks %>% 
        </p>